XVM_token = "328a3d28-b7ad-417b-d76e-c26ded2e1279"
XVM_API = 4.0

wg_app_id = '44211a8d5fcaf71d7849e539f406f6f1'

url_tankopedia = 'https://api.worldoftanks.eu/wot/encyclopedia/info/?application_id={app_id}'
url_tank_basic = 'https://api.worldoftanks.eu/wot/encyclopedia/vehicles/?application_id={app_id}&tank_id={tank_id}'
url_tank_info = 'https://api.worldoftanks.eu/wot/encyclopedia/tankinfo/?application_id={app_id}&tank_id={tank_id}'
url_tank_configs = 'https://api.worldoftanks.eu/wot/encyclopedia/vehicleprofile/?application_id={app_id}&tank_id={tank_id}'

url_modules = {'vehicleGun' : 'https://api.worldoftanks.eu/wot/encyclopedia/tankguns/?application_id={app_id}&module_id={module_id}',
	'vehicleEngine' : 'https://api.worldoftanks.eu/wot/encyclopedia/tankengines/?application_id={app_id}&module_id={module_id}',
	'vehicleRadio' : 'https://api.worldoftanks.eu/wot/encyclopedia/tankradios/?application_id={app_id}&module_id={module_id}',
	'vehicleTurret' : 'https://api.worldoftanks.eu/wot/encyclopedia/tankturrets/?application_id={app_id}&module_id={module_id}',
	'vehicleChassis' : 'https://api.worldoftanks.eu/wot/encyclopedia/tankchassis/?application_id={app_id}&module_id={module_id}'}

tgg_versions = 'https://tanks.gg/api/versions'
tgg_tank_list = 'https://tanks.gg/api/{version}/list'
tgg_tank = 'https://tanks.gg/api/{version}/tank/{tank}'
tgg_accessories = 'https://tanks.gg/api/{version}/accessories'

player_db = 'player_db'

country_translate = { 'AL' : 'Albania',
	 'AD' : 'Andorra',
	 'AT' : 'Austria',
	 'BY' : 'Belarus',
	 'BE' : 'Belgium',
	 'BA' : 'Bosnia and Herzegovina',
	 'BG' : 'Bulgaria',
	 'HR' : 'Croatia',
	 'CZ' : 'Czech Republic',
	 'DK' : 'Denmark',
	 'EE' : 'Estonia',
	 'FI' : 'Finland',
	 'FR' : 'France',
	 'DE' : 'Germany',
	 'GR' : 'Greece',
	 'VA' : 'Holy See (Vatican City State)',
	 'HU' : 'Hungary',
	 'IS' : 'Iceland',
	 'IE' : 'Ireland',
	 'IT' : 'Italy',
	 'LV' : 'Latvia',
	 'LI' : 'Liechtenstein',
	 'LT' : 'Lithuania',
	 'LU' : 'Luxembourg',
	 'MK' : 'the Former Yugoslav Republic of Macedonia',
	 'MT' : 'Malta',
	 'MD' : 'Republic of Moldova',
	 'MC' : 'Monaco',
	 'ME' : 'Montenegro',
	 'NL' : 'Netherlands',
	 'NO' : 'Norway',
	 'PL' : 'Poland',
	 'PT' : 'Portugal',
	 'RO' : 'Romania',
	 'RU' : 'Russian Federation',
	 'SM' : 'San Marino',
	 'RS' : 'Serbia',
	 'SK' : 'Slovakia',
	 'SI' : 'Slovenia',
	 'ES' : 'Spain',
	 'SE' : 'Sweden',
	 'CH' : 'Switzerland',
	 'TR' : 'Turkey',
	 'UA' : 'Ukraine',
	 'GB' : 'United Kingdom',
	 'AG' : 'Antigua and Barbuda',
	 'BS' : 'Bahamas',
	 'BB' : 'Barbados',
	 'BZ' : 'Belize',
	 'CA' : 'Canada',
	 'CR' : 'Costa Rica',
	 'CU' : 'Cuba',
	 'DM' : 'Dominica',
	 'DO' : 'Dominican Republic',
	 'SV' : 'El Salvador',
	 'GD' : 'Grenada',
	 'GT' : 'Guatemala',
	 'HT' : 'Haiti',
	 'HN' : 'Honduras',
	 'JM' : 'Jamaica',
	 'MX' : 'Mexico',
	 'NI' : 'Nicaragua',
	 'PA' : 'Panama',
	 'KN' : 'Saint Kitts and Nevis',
	 'LC' : 'Saint Lucia',
	 'VC' : 'Saint Vincent and the Grenadines',
	 'TT' : 'Trinidad and Tobago',
	 'US' : 'United States',
	 'AR' : 'Argentina',
	 'BO' : 'Plurinational State of Bolivia',
	 'BR' : 'Brazil',
	 'CL' : 'Chile',
	 'CO' : 'Colombia',
	 'EC' : 'Ecuador',
	 'GY' : 'Guyana',
	 'PY' : 'Paraguay',
	 'PE' : 'Peru',
	 'SR' : 'Suriname',
	 'UY' : 'Uruguay',
	 'VE' : 'Bolivarian Republic of Venezuela',
	 'AF' : 'Afghanistan',
	 'AM' : 'Armenia',
	 'AZ' : 'Azerbaijan',
	 'BH' : 'Bahrain',
	 'BD' : 'Bangladesh',
	 'BT' : 'Bhutan',
	 'BN' : 'Brunei Darussalam',
	 'KH' : 'Cambodia',
	 'CN' : 'China',
	 'CY' : 'Cyprus',
	 'GE' : 'Georgia',
	 'IN' : 'India',
	 'ID' : 'Indonesia',
	 'IR' : 'Islamic Republic of Iran',
	 'IQ' : 'Iraq',
	 'IL' : 'Israel',
	 'JP' : 'Japan',
	 'JO' : 'Jordan',
	 'KZ' : 'Kazakhstan',
	 'KP' : 'Democratic People`s Republic of Korea',
	 'KR' : 'Republic of Korea',
	 'KW' : 'Kuwait',
	 'KG' : 'Kyrgyzstan',
	 'LA' : 'Lao People`s Democratic Republic',
	 'LB' : 'Lebanon',
	 'MY' : 'Malaysia',
	 'MV' : 'Maldives',
	 'MN' : 'Mongolia',
	 'MM' : 'Myanmar',
	 'NP' : 'Nepal',
	 'OM' : 'Oman',
	 'PK' : 'Pakistan',
	 'PS' : 'State of Palestine',
	 'PH' : 'Philippines',
	 'QA' : 'Qatar',
	 'SA' : 'Saudi Arabia',
	 'SG' : 'Singapore',
	 'LK' : 'Sri Lanka',
	 'SY' : 'Syrian Arab Republic',
	 'TW' : 'Province of China Taiwan',
	 'TJ' : 'Tajikistan',
	 'TH' : 'Thailand',
	 'TL' : 'Timor-Leste',
	 'TM' : 'Turkmenistan',
	 'AE' : 'United Arab Emirates',
	 'UZ' : 'Uzbekistan',
	 'VN' : 'Viet Nam',
	 'YE' : 'Yemen',
	 'AU' : 'Australia',
	 'CK' : 'Cook Islands',
	 'FJ' : 'Fiji',
	 'KI' : 'Kiribati',
	 'MH' : 'Marshall Islands',
	 'FM' : 'Federated States of Micronesia',
	 'NR' : 'Nauru',
	 'NZ' : 'New Zealand',
	 'NU' : 'Niue',
	 'PW' : 'Palau',
	 'PG' : 'Papua New Guinea',
	 'WS' : 'Samoa',
	 'SB' : 'Solomon Islands',
	 'TO' : 'Tonga',
	 'TV' : 'Tuvalu',
	 'VU' : 'Vanuatu',
	 'DZ' : 'Algeria',
	 'AO' : 'Angola',
	 'BJ' : 'Benin',
	 'BW' : 'Botswana',
	 'BF' : 'Burkina Faso',
	 'BI' : 'Burundi',
	 'CM' : 'Cameroon',
	 'CV' : 'Cape Verde',
	 'CF' : 'Central African Republic',
	 'TD' : 'Chad',
	 'KM' : 'Comoros',
	 'CG' : 'Congo',
	 'CI' : 'Côte d`Ivoire',
	 'CD' : 'Democratic Republic of the Congo',
	 'DJ' : 'Djibouti',
	 'EG' : 'Egypt',
	 'GQ' : 'Equatorial Guinea',
	 'ER' : 'Eritrea',
	 'ET' : 'Ethiopia',
	 'GA' : 'Gabon',
	 'GM' : 'Gambia',
	 'GH' : 'Ghana',
	 'GN' : 'Guinea',
	 'GW' : 'Guinea-Bissau',
	 'KE' : 'Kenya',
	 'LS' : 'Lesotho',
	 'LR' : 'Liberia',
	 'LY' : 'Libya',
	 'MG' : 'Madagascar',
	 'MW' : 'Malawi',
	 'ML' : 'Mali',
	 'MR' : 'Mauritania',
	 'MU' : 'Mauritius',
	 'MA' : 'Morocco',
	 'MZ' : 'Mozambique',
	 'NA' : 'Namibia',
	 'NE' : 'Niger',
	 'NG' : 'Nigeria',
	 'RW' : 'Rwanda',
	 'ST' : 'Sao Tome and Principe',
	 'SN' : 'Senegal',
	 'SC' : 'Seychelles',
	 'SL' : 'Sierra Leone',
	 'SO' : 'Somalia',
	 'ZA' : 'South Africa',
	 'SS' : 'South Sudan',
	 'SD' : 'Sudan',
	 'SZ' : 'Swaziland',
	 'TZ' : 'Tanzania United Republic of',
	 'TG' : 'Togo',
	 'TN' : 'Tunisia',
	 'UG' : 'Uganda',
	 'ZM' : 'Zambia',
	 'ZW' : 'Zimbabwe' }